### ISSUE TITLE
Issue while trying to run Grails 7 on intel chip system(MAC)

### ISSUE THREAD

**Issue by jamesfredley** [grails/grails-forge#549]
### Discussed in https://github.com/apache/grails-core/discussions/14094

<div type='discussions-op-text'>

<sup>Originally posted by **HrishavRS** March 31, 2025</sup>
Hi, while running grails application on intel chip in my mac following issue is seen.

<img width="857" alt="Screenshot 2025-03-31 at 10 30 28 AM" src="https://github.com/user-attachments/assets/df8894b4-117d-4ae4-aed7-dbe40eb71d05" />

In Use
Grails : 7.0.0-M3
Gradle : 8.13
Java : 17.0.13-amzn 
 
This Grails version i fine on M-series Mac.

Am I missing something?</div>

**Comment by jamesfredley** [comment]
@HrishavRS Grails publishes two binaries to for macOS, an ARM version and an x86_64 version.

You can see both on https://github.com/apache/grails-forge/releases/tag/v7.0.0-M3.   You will want [grails-darwin-amd64-v7.0.0-M3.zip](https://github.com/apache/grails-forge/releases/download/v7.0.0-M3/grails-darwin-amd64-v7.0.0-M3.zip)

Did SDKMan give you the incorrect version?

**Comment by jamesfredley** [comment]
This was fixed on https://github.com/apache/grails-forge/issues/538 after the 7.0.0-M3 milestone.  It is working in 7.0.0-SNAPSHOT and will work in the 7.0.0-M4 which will be the first milestone under Apache.

**Comment by HrishavRS** [comment]
I cannot be sure on that, sdkman doesn't provide the option to choose the version for the package in the question.
 
However i am still facing bad CPU executable from the provided amd64 version.
 
I tested this on other 3 Mac with Intel Chip and all are facing the same issue, 
However on M-Series Mac, This issue is not observed.
 
Processor in use for Intel Chip : 2.6 GHz 6-Core Intel Core i7

I will look into M4 version once it's released, Thanks!

**Comment by jamesfredley** [comment]
@HrishavRS Please check https://github.com/grails/grails-forge/actions/runs/13723939397/artifacts/2711836830 it was build with the macos-13
